// <auto-generated />
using System;
using Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260205111503_RemovePanelTobacconistNavigation")]
    partial class RemovePanelTobacconistNavigation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Core.Entities.Barcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TobacconistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TobacconistId");

                    b.ToTable("Barcodes");
                });

            modelBuilder.Entity("Catalog.Core.Entities.Brand", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("Catalog.Core.Entities.Panel", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Binder")
                        .HasColumnType("text");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Filler")
                        .HasColumnType("text");

                    b.Property<string>("MasterLine")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NumberInBox")
                        .HasColumnType("integer");

                    b.Property<string>("Origin")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int?>("Ring")
                        .HasColumnType("integer");

                    b.Property<string>("RollingType")
                        .HasColumnType("text");

                    b.Property<string>("Shape")
                        .HasColumnType("text");

                    b.Property<int?>("SmokingTime")
                        .HasColumnType("integer");

                    b.Property<int?>("Strength")
                        .HasColumnType("integer");

                    b.Property<string>("TobacconistCode")
                        .HasColumnType("text");

                    b.Property<Guid?>("TobacconistId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("Wrapper")
                        .HasColumnType("text");

                    b.Property<int?>("WrapperColor")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("BrandId");

                    b.ToTable("Panels");
                });

            modelBuilder.Entity("Catalog.Core.Entities.Tobacconist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CurrentPricingValidity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NextPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("NextPricingValidity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NextStackPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("PanelId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PriceKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StackPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("StackType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tobacconists");
                });

            modelBuilder.Entity("Catalog.Core.Entities.Barcode", b =>
                {
                    b.HasOne("Catalog.Core.Entities.Tobacconist", null)
                        .WithMany("Barcodes")
                        .HasForeignKey("TobacconistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Core.Entities.Panel", b =>
                {
                    b.HasOne("Catalog.Core.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Catalog.Core.Entities.Tobacconist", b =>
                {
                    b.Navigation("Barcodes");
                });
#pragma warning restore 612, 618
        }
    }
}
