// <auto-generated />
using System;
using Catalog.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260204155310_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Core.Entities.Barcode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("TobacconistId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TobacconistId");

                    b.ToTable("Barcodes");
                });

            modelBuilder.Entity("Catalog.Core.Entities.Tobacconist", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CurrentPricingValidity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NextPrice")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("NextPricingValidity")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NextStackPrice")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceKg")
                        .HasColumnType("numeric");

                    b.Property<decimal>("StackPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("StackType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tobacconists");
                });

            modelBuilder.Entity("Catalog.Core.Entities.Barcode", b =>
                {
                    b.HasOne("Catalog.Core.Entities.Tobacconist", null)
                        .WithMany("Barcodes")
                        .HasForeignKey("TobacconistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Catalog.Core.Entities.Tobacconist", b =>
                {
                    b.Navigation("Barcodes");
                });
#pragma warning restore 612, 618
        }
    }
}
